### ISSUE TITLE
Question about Psr16

### ISSUE THREAD

**Issue by Awilum** [PHPSocialNetwork/phpfastcache#750]
Hello!

As I understand Psr16 may help to work with phpfastcache in simple way like it is with Doctrine Cache.
But will I able to access any other methods that phpfastcache provides ?

**Comment by Geolim4** [comment]
Hello,

Internally the PSR16 adapter encapsulates calls to the native PSR6 methods of Phpfastcache.

Since the instance of cache are stored into a protected property you wont will be able to access to the Phpfastcache instance of the Psr16 adapter through `getInternalCacheInstance()` method:
https://github.com/PHPSocialNetwork/phpfastcache/blob/edb91d88b26723ac7317c01c5cfe3977582035ed/lib/Phpfastcache/Helper/Psr16Adapter.php#L236

Or you can use standard CacheManager to get a regular PSR6 instance of cache and deal with them according PSR6 specs. 

As you want !

Cheers,
Georges

**Comment by Geolim4** [comment]
Wiki of PSr16 adapter here:

https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Psr16-adapter

**Comment by Awilum** [comment]
I have one more question, related to options. 

I see there is doc about options
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/OPTIONS.md

but seems there are not all options described, for e.g. if I will go here
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/examples/cassandra.php
I see more options required for this driver but they are not described anywhere, and for other drivers

**Comment by Geolim4** [comment]
`\Phpfastcache\Config\Config` is an alias of `\Phpfastcache\Config\ConfigurationOption`

However each driver has its own config class that extends `\Phpfastcache\Config\Config` with customs options.

You can either use `\Phpfastcache\Config\Config` is you want to use Phpfastcache default's config or use the custom Config class of the backend:
`\Phpfastcache\Drivers\Cassandra\Config`

**Comment by Awilum** [comment]
@Geolim4 so the good way is use each custom config class and it is options for each driver ?

**Comment by Geolim4** [comment]
Ideally, yes. Only in the case you can't use the default configuration provided by Phpfastcache :)

**Comment by Awilum** [comment]
I am trying to create config for each driver, and I have some misunderstanding on this...

https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/OPTIONS.md
> * Drivers like Files, Sqlite, Leveldb, etc.

so, for files: 
```
  drivers:
    files:
      path: 'cache'
      secure_file_manipulation: false
      htaccess: true
      security_key: ''
      cache_file_extension: 'txt'
      item_detailed_date: false
      auto_tmp_fallback: false
      default_ttl: 900
      default_key_hash_function: 'md5'
      default_file_name_hash_function: 'md5'
      default_chmod: 0777
      prevent_cache_slams: false
      cache_slams_timeout: 15
```
this is okey, but when I go to next _Drivers like Files, Sqlite, Leveldb, etc._ - Sqlite

```
    sqlite:
      path: 'cache'
      secure_file_manipulation: false
      htaccess: true
      security_key: ''
      cache_file_extension: 'txt'
      item_detailed_date: false
      auto_tmp_fallback: false
      default_ttl: 900
      default_key_hash_function: 'md5'
      default_file_name_hash_function: 'md5'
      default_chmod: 0777
      prevent_cache_slams: false
      cache_slams_timeout: 15
```
not all of this options are really needed for Sqlite ? how to determine what exactly options need to each driver ?
