### ISSUE TITLE
Github issues - Testing new template form

### ISSUE THREAD

**Issue by Geolim4** [PHPSocialNetwork/phpfastcache#871]
### What type of issue is this?

Other (Please Specify)

### Operating system + version

Ubuntu 20.04

### PHP version

8.0.2

### Connector/Database version (if applicable)

Redis 7.0.1 + PECL Extension 5.3.6

### Phpfastcache version

9.1.1 🔶

### Describe the issue you're facing

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ultricies ex vel purus consectetur hendrerit. Donec eu erat libero. Quisque volutpat et justo non ullamcorper. Curabitur diam lorem, faucibus a ligula sit amet, ornare faucibus justo. Pellentesque ultrices feugiat libero, efficitur fringilla diam posuere in. Phasellus justo dolor, rutrum ut est eu, volutpat facilisis justo. 

```
Mauris tincidunt nisi id metus pharetra hendrerit. Cras commodo, leo vitae scelerisque consequat, quam ligula eleifend nisi, vel tincidunt lacus quam nec nulla. Vivamus felis mi, maximus vel lectus eget, lacinia interdum sem. Pellentesque posuere, libero a euismod imperdiet, orci ex finibus turpis, nec accumsan magna erat ut lacus. Duis eget ex dolor. Donec id arcu quis dui aliquet condimentum euismod ornare ligula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec posuere turpis. Etiam eu lacinia sapien.
```

Aliquam viverra erat a neque pulvinar volutpat. Duis condimentum imperdiet est, in varius felis dignissim et. Praesent sit amet tempus quam. Duis in ex eget odio vulputate iaculis. **Nam ut velit risus**. Nulla ex lorem, suscipit nec nunc in, commodo euismod velit. Nam fermentum dapibus dui, quis consectetur libero luctus at. Vestibulum in lacus ut justo tincidunt hendrerit. Suspendisse congue magna vitae ullamcorper laoreet. Aenean at scelerisque dolor, in viverra tellus. Nunc molestie in purus vel commodo. Quisque maximus, turpis non egestas posuere, arcu justo congue nulla, ac commodo nisi lacus nec enim. 

### Expected behavior

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nisi mauris, accumsan a mollis non, elementum in felis. Vestibulum sem velit, malesuada ac purus id, porta congue diam. Vivamus porta mattis tincidunt. Nullam metus mi, lobortis dictum lacus tincidunt, egestas imperdiet nibh. Nullam egestas ligula quis sem efficitur ullamcorper. Duis pretium hendrerit dui vitae venenatis. Proin ultrices in arcu at lacinia. Cras ullamcorper lorem pharetra quam dictum, vel consequat lacus luctus. Vivamus sollicitudin lectus libero, non tincidunt tellus dignissim id. Etiam sem urna, varius in nisi ut, gravida ultrices nunc. In hac habitasse platea dictumst. Praesent a augue non justo euismod finibus eget at dolor. Sed vestibulum quis ligula vitae placerat. Cras a enim et nibh molestie hendrerit at sed est. Nullam facilisis sagittis sollicitudin. Nulla eu placerat ligula.

Aliquam eleifend fringilla est. Sed sit amet magna maximus, vulputate augue et, interdum mi. Morbi vitae fermentum diam, quis lobortis eros. Donec felis erat, ultricies at leo ornare, eleifend vulputate nunc. Nam ornare, velit ac elementum posuere, est dolor dapibus sem, sit amet viverra nunc justo in velit. Morbi augue neque, iaculis in fermentum viverra, facilisis eu erat. Mauris tempus orci ligula, in rutrum ex ultrices sed. Suspendisse mattis posuere enim, nec viverra elit bibendum id. Nam faucibus erat gravida, finibus mi nec, condimentum velit. Maecenas vel erat nec ex sollicitudin dignissim id ac libero. Nulla ultrices dui at ligula bibendum varius. Phasellus quis cursus arcu. Sed eget dapibus sapien. Donec sagittis tortor non ante fringilla, a posuere arcu ornare. Aenean nisi sem, consequat sit amet est vitae, sollicitudin rutrum ipsum. 

### Code sample (optional)

```yml
name: "Ask a question"
title: "<NAME THE QUESTION>"
description: Ask a question about Phpfastcache
labels: ["Needs triage 🔎"]
assignees: ["Geolim4"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Are you looking for development help?**
        ↩ Please note that we cannot provide assistance on web development. We recommend asking around on a dedicated help forum like StackOverflow.

        ### Issue etiquette
        
        When opening a new ticket, please:
        - Follow the project's [Code of Conduct](https://github.com/PHPSocialNetwork/phpfastcache/blob/master/CODE_OF_CONDUCT.md) as well as the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines).
        - Check for an [existing question](https://github.com/PHPSocialNetwork/phpfastcache/issues) first. If someone else has opened a similar question, please upvote their question rather than creating another one.
        - Keep questions relevant to the project. Irrelevant questions will be automatically closed and marked as spam, and repeated offenses may result in exclusion from our organization.
        - Provide as much detail as possible. The more detail you are able to provide, the better!
        ---

  - type: textarea
    id: the_question
    attributes:
      label: What's your question ?
      description: Feel free to ask !
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Can you link to any release notes, ideas, pull requests, or Stack-Overflow link related to this?
  - type: textarea
    id: more_info
    attributes:
      label: Do you have anything more you want to share? (optional)
      description: For example, screenshots, screen recordings, or sample code, logs, etc.
  - type: markdown
    attributes:
      value: |
        ---
        You're finished 👏 
        The following fields are prefilled and should not be modified. Please click **Submit**.

```

### Suggestion to fix the issue (optional)

**Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean facilisis quis purus nec dictum. Nam non placerat massa. Duis risus diam, consequat scelerisque congue ut, euismod a metus. Nullam pulvinar risus vitae iaculis porttitor. In porttitor nec magna non suscipit. Sed posuere arcu nunc, vel commodo nulla maximus vitae. Nulla eget nisi eu arcu aliquam pretium sed sit amet nibh. Sed lacus orci, rhoncus quis massa nec, sodales molestie orci. Sed at mollis nisl. Vestibulum pulvinar magna ex, vitae sodales felis tincidunt finibus. Donec dapibus fermentum ante, quis molestie tortor commodo ut. Cras a nisl massa.**

_Donec eu ante sit amet mi ornare imperdiet. Nunc imperdiet lacus nunc, nec facilisis arcu finibus id. Mauris pretium congue turpis, elementum molestie urna maximus vitae. Nunc vestibulum erat condimentum laoreet bibendum. Suspendisse interdum bibendum ex. Nam dictum arcu quis euismod imperdiet. Fusce congue maximus lacus eu pretium. Donec molestie molestie porttitor. Pellentesque eget molestie est. Morbi non dolor molestie magna porta gravida. Nunc fringilla neque non euismod euismod. Phasellus aliquet tincidunt dui eget mattis. Etiam convallis malesuada pretium. Mauris et libero eu felis gravida porta. Nunc et urna fringilla, placerat turpis sed, imperdiet orci. Donec accumsan mauris sed suscipit dictum._ 

### 1
![image](https://user-images.githubusercontent.com/1332071/172927907-2b0c30c6-69d8-4538-a1de-c11aa7fa3706.png)

### 2
![image](https://user-images.githubusercontent.com/1332071/172927922-d07db7bc-b6f1-42c7-bd71-7709387d6435.png)

### Have you searched in our Wiki before posting ?

- [x] I have searched over the Wiki
